services:
  task_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_REDIS_HOST: ${REDIS_HOST}
      SPRING_REDIS_PORT: 6379
      SECURITY_SECRET: ${SECURITY_SECRET}
      EXPIRATION_TIME: ${EXPIRATION_TIME}
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - redis
    networks:
      - task-net

  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: task-postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - task-net

  redis:
    image: ${REDIS_IMAGE}
    container_name: task-redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      REDIS_HOST: ${REDIS_HOST}
    env_file:
      - .env
    networks:
      - task-net

networks:
  task-net:
    driver: bridge
